// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffnqzcmzuofzzodufsbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbnF6Y216dW9menpvZHVmc2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQ1NjEsImV4cCI6MjA3MzM3MDU2MX0.lnALMAkzCjFXoOI3QBwF6WHd3vlTwB-Du45UFRhEH20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});